import 'semantic-ui-css/semantic.css'
// import 'semantic-ui-css/components/button.css'
// import 'semantic-ui-css/components/form.css'
// import 'semantic-ui-css/components/grid.css'
// import 'semantic-ui-css/components/header.css'
// import 'semantic-ui-css/components/icon.css'
// import 'semantic-ui-css/components/image.css'
// import 'semantic-ui-css/components/input.css'
// import 'semantic-ui-css/components/message.css'
// import 'semantic-ui-css/components/segment.css'
// import 'semantic-ui-css/components/table.css'
// import 'semantic-ui-css/components/menu.css'
// import 'semantic-ui-css/components/dropdown.css'
// import 'semantic-ui-css/components/container.css'
// import 'semantic-ui-css/components/statistic.css'
// import 'semantic-ui-css/components/modal.css'
